prefix                 = "cmaz"
suffix_rg              = "rg"
suffix_vnet            = "vnet"
suffix_storage         = "sa"
subnet_name            = ["frontend", "backend"]
vnet_address_space     = ["10.0.0.0/16"]
subnet1_address_prefix = ["10.0.1.0/24"]
subnet2_address_prefix = ["10.0.2.0/24"]
project_code           = "ph0p7o3b-mod3"
project_code_short     = "ph0p7o3b"
location               = "eastus"
tag                    = "alejandro_villarreal@epam.com"